project:
  type: website

website:
  title: "ReproducibiliTea Sheffield 2023-12-06"
  site-url: https://ns-rse.github.io/reproducibilitea-sheffield-2023-12-06
  description: "Discussion of the paper Protzko et al. (2023) High replicability of newly discovered social-behavioural findings is achievable"
